name: Test Manual Workflow

on:
  workflow_dispatch:
    inputs:
      Environment:
        description: "The environnement, I need to deploy on"
        required: true
        default: '/dev'

jobs:
    manual-job:
        runs-on: ubuntu-latest

        steps:
          - name: Example
            run: |
              echo "Mon exemple"
              echo "Env Name: ${{ github.event.inputs.Environment }}"
          - name: Github Variable
            run: echo '${{ toJSON(github) }}'

          - name: Runner Variable
            run: echo '${{ toJSON(runner) }}'
            
          - name: Secrets Variable
            run: echo '${{ toJSON(secrets) }}'
            
            
            


