name: Test Manual Workflow

on:
  workflow_dispatch:
    inputs:
      Environnements:
        description: "The environnement, I nedd to deploy on"
        required: true
        default: '/dev'

jobs:
    manual-job:
        runs-on: ubuntu-latest

        steps:
          - name: Example
            run: |
            echo "Mon exemple"
            echo "Env Name: ${{ github.event.inputs.Environnement }}"
